### PR TITLE
fixed https://github.com/silenceper/wechat/issues/203

### PR DESCRIPTION
**Pull request by ckeyer**
因为存在变量作为变量名，暂时只想到用map替代整个结构体

### CODE REVIEW

**Comment by ckeyer** [comment]
fixed https://github.com/silenceper/wechat/issues/203

**Comment by ckeyer** [comment]
相关文档 https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_7&index=8

**Comment by ckeyer** [comment]
@airylinus PTAL

**Comment by silenceper** [comment]
fixed in #203

**Pull request closed without merging**
