### PR TITLE
fix:模板消息小程序跳转地址字段名

### PR DESCRIPTION
**Pull request by liuy-dev**
微信官方文档错误模板消息pagepath字段有误
改为page

### CODE REVIEW

**Comment by liuy-dev** [comment]
快点合上去吧，大半夜踩坑。。。

**Comment by evanzme** [comment]
官方文档就是pagepath呀，https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html

<blockquote><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html">模板消息 | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Comment by evanzme** [comment]
https://developers.weixin.qq.com/community/develop/doc/000e00c6e38298e4734c09a6d56000?highLine=pagepath

<blockquote><div><strong><a href="https://developers.weixin.qq.com/community/develop/doc/000e00c6e38298e4734c09a6d56000?highLine=pagepath">公众号模板消息跳转小程序，小程序 pagepath 参数有问题，应该是page | 微信开放社区</a></strong></div><div>https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html</div></blockquote>

**Comment by evanzme** [comment]
> https://developers.weixin.qq.com/community/develop/doc/000e00c6e38298e4734c09a6d56000?highLine=pagepath
> 
> > **[公众号模板消息跳转小程序，小程序 pagepath 参数有问题，应该是page | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000e00c6e38298e4734c09a6d56000?highLine=pagepath)**https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html

官方回复：是pagepath

<blockquote><div><strong><a href="https://developers.weixin.qq.com/community/develop/doc/000e00c6e38298e4734c09a6d56000?highLine=pagepath">公众号模板消息跳转小程序，小程序 pagepath 参数有问题，应该是page | 微信开放社区</a></strong></div><div>https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html</div></blockquote>
<blockquote><div><strong><a href="https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html">模板消息 | 微信开放文档</a></strong></div><div>微信开发者平台文档</div></blockquote>

**Pull request closed without merging**
